export const CREATE_VILLAGER = "CREATE_VILLAGER";
export const RETRIEVE_VILLAGERS = "RETRIEVE_VILLAGERS";
export const UPDATE_VILLAGER = "UPDATE_VILLAGER";
export const DELETE_VILLAGER = "DELETE_VILLAGER";
export const DELETE_ALL_VILLAGERS = "DELETE_ALL_VILLAGERS";